name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create build folder
        run: mkdir -p build

      - name: Pack extension
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: .
          zipFilePath: build/extension.zip

      - name: Build CRX
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: build/extension.zip
          crxFilePath: build/extension.crx
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
          keyFormat: PEM

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            build/extension.zip
            build/extension.crx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
